title: Speedshop - Ruby on Rails performance consulting
email: nate.berkopec@speedshop.co
description: >
  Speedshop is a Ruby on Rails performance consultancy that
  optimizes the full stack - frontend, backend and environment - to generate
  revenue and cut scaling costs for businesses on Rails. Fast sites are
  profitable sites. Speed is a feature.
baseurl: ""
url: "https://www.speedshop.co"
collections:
  posts:
    permalink: "blog/:title/"
plugins:
  - jekyll-sitemap
markdown: kramdown
kramdown:
  auto_ids: true
encoding: utf-8
sass:
  sourcemap: never
exclude:
   - _h2o
   - _scripts
   - Procfile
   - wercker.yml
   - Gemfile
   - Gemfile.lock
